services:
  - type: web
    name: citypharm
    env: python
    buildCommand: "./render_build.sh && pip install -r requirements.txt"
    startCommand: "gunicorn citypharm.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: citypharm_glavnaia_apteka
          property: connectionString
