# Generated by Django 5.2.7 on 2025-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название аптеки')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('rent_contract', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Договор аренды (PDF/Word)')),
                ('cadastral_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кадастровый номер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='Фото аптеки')),
                ('opened_date', models.DateField(blank=True, null=True, verbose_name='Дата открытия')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
    ]
