# Generated by Django 5.2.7 on 2025-10-17 11:18

import branches.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='cadastral_number',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='image',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opened_date',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone',
        ),
        migrations.AddField(
            model_name='branch',
            name='cadastral_doc',
            field=models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_branches, verbose_name='Кадастр'),
        ),
        migrations.AddField(
            model_name='branch',
            name='gpp_certificate',
            field=models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_branches, verbose_name='GPP сертификат'),
        ),
        migrations.AddField(
            model_name='branch',
            name='guvohnoma',
            field=models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_branches, verbose_name='Гувохнома'),
        ),
        migrations.AddField(
            model_name='branch',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_branches, verbose_name='Лицензия'),
        ),
        migrations.AddField(
            model_name='branch',
            name='sop_doc',
            field=models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_branches, verbose_name='СОП'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название филиала'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='rent_contract',
            field=models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_branches, verbose_name='Договор аренды'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('order_doc', models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_employees, verbose_name='Приказ')),
                ('meh_doc', models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_employees, verbose_name='Мехнат шартнома')),
                ('instruction_doc', models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_employees, verbose_name='Должностная инструкция')),
                ('med_book', models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_employees, verbose_name='Мед книжка')),
                ('gpp_certificate', models.FileField(blank=True, null=True, upload_to=branches.models.upload_to_employees, verbose_name='GPP сертификат')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='branches.branch', verbose_name='Филиал')),
            ],
        ),
    ]
